; LockOnFovChanger external configuration
; Read once when the Lua mod loads. Restart the game after editing.
; Console command is supported, use "clo ?" to see command list.
; Game default settings as below, you can change them to your liking.
;LockOnFOV=90    <- FOV setting
;LockOnOffsetZ=0 <- camera pitch
;EnemyOffset=120 <- enemy position offset

FOVEnabled=true
LockOnFOV=120
LockOnOffsetZ=90
EnemyOffset=-180
EnableLog=false
