; LockOnFovChanger external configuration
; Read once when the Lua mod loads. Restart the game after editing.

; Normal in-game FOV is 90, LockOnFOV is the FOV value after locked on enemy.
; Set to 70 to zoom in and set to 120 to zoom out.

; PageDown key toogles the mod

FOVEnabled=true
LockOnFOV=110
CameraOffsetFix=true
EnableLog=false